### PR TITLE
gh-234: Fix typo in helm index.yaml

### LINKED ISSUE #234: [hdfs] Chart repository does not contain 1.0.0
Hi,

The selected URL returns with 404:

image

Great chart BTW!

### PR DESCRIPTION
**Pull request by t92549**
Fixed typo introduced in the manual commit fix: f1bf9a4d6dceeb25036399e004624e5db71de2d5

# Related Issue

- Resolve #234

### CODE REVIEW

**Comment by t92549** [comment]
Ignore ci for this commit, should not run on `gh-pages`

**Comment by t92549** [comment]
I am not entirely sure why it does fail on this branch though...

**Review by GCHQDeveloper314 — APPROVED** [review]

**Comment by t92549** [comment]
I am not sure the ci should fail though, maybe it is okay but seems weird

**Comment by t92549** [comment]
To be looked at later: https://github.com/gchq/gaffer-docker/issues/236

**Pull request merged**
